# Generated by Django 2.1 on 2019-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('interaction_time', models.DateTimeField(verbose_name='interaction time')),
                ('interaction_type', models.CharField(max_length=200)),
                ('button_name', models.CharField(max_length=200)),
            ],
        ),
    ]
