# Generated by Django 2.1 on 2019-12-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='kiosk_id',
            field=models.IntegerField(null=True),
        ),
    ]
