# Generated by Django 2.1 on 2019-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kiosk', '0002_engagement_kiosk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='geolocation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
