# Generated by Django 2.1.15 on 2019-12-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kiosk', '0003_engagement_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='button_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
